### ISSUE TITLE
Feedback/comment

### ISSUE THREAD

**Issue by usmarine993** [Cisco-Talos/GhIDA#11]
Sorry this is more of a comment/feedback and not exactly an issue:

I tried it on Ida Pro 7.X and it worked as it supposed to however I also tried it on Ida Free 7.X and for some reason the plugin doesn't even show up in the Ida plugin menu. Any idea why?

**Comment by jimmy-sonny** [comment]
Unfortunately this plugin is not compatible with the IDA Freeware version. IDA Pro 7.x is required.
