### ISSUE TITLE
Port plugin to Python3

### ISSUE THREAD

**Issue by trib0r3** [Cisco-Talos/GhIDA#14]
Hi, because Ida is slowly [moving to python3](https://www.hex-rays.com/products/ida/support/ida74_idapython_python3/), it would be nice to have this plugin ported to python3. 

I started working on this ([diff](https://github.com/Cisco-Talos/GhIDA/compare/master...trib0r3:master)), but I have still some unresolved issues which requires deeper debug, like decompilation is failing - probably somebody from authors of this plugin should check diff.

**Comment by jimmy-sonny** [comment]
Hi @trib0r3!

Thanks a lot for your contribution. Starting from your diff, I fixed other small bugs, and I've just pushed on the dev-python3 branch an IDA 7.4 - Python3 version of the plugin (ffa6023).

I've tested it on Ubuntu 18.04, IDA 7.4.191112 and Python 3.6.7.

Please, test it, and let me know if it works for you too.

**Comment by trib0r3** [comment]
Hi @jimmy-sonny!

I've tested GhIDA on Windows IDA 7.4.191112 and python 3.8.1 -> it works :D
