### ISSUE TITLE
Global name "CLexer" not defined?

### ISSUE THREAD

**Issue by tthtlc** [Cisco-Talos/GhIDA#17]
![image](https://user-images.githubusercontent.com/179509/75499375-c5048c00-5a04-11ea-9e2a-6af8506aa14f.png)

I got this error immediately after installation and attempt to decompile an example program in IDA 7.2 (Linux version), and Ghidra is 9.1 and 9.1.2 all gave the same error.

Any ideas how to overcome it?

This error is a showstopper, as there is no decompilation at all.

**Comment by jimmy-sonny** [comment]
Can you please check that you have correctly installed pygments in the Python version used by IDA?
