### ISSUE TITLE
Ghidra Headless Analysis Failure: No JSON object could be decoded

### ISSUE THREAD

**Issue by k4yt3x** [Cisco-Talos/GhIDA#18]
## System Information

- GhIDA Versions:
  - Release v0.1
  - Master at commit https://github.com/Cisco-Talos/GhIDA/commit/d153e0dddf437b96dbbcd9be23774a538f614317
- OS: Windows 10 Professional `1909`
- Virtualization Host: VMWare Workstation Pro `15.5.2`
- Ghidra: `9.1.2`
- IDA Pro: `7.3`
- JDK Versions:
  - `13.0.2`
  - `11.0.6`
- Python Version: `2.7.13`

## Symptoms

When attempting to perform analysis on the GreenBug Trojan, the Hexrays decompiler decompiles successfully, while the Ghidra decompiler displays the following error:

> GhIDA:: [!] Decompilation error - timeout reached
> GhIDA:: [!] No JSON object could be decoded
> GhIDA:: [!] Ghidra headless analysis failed
> GhIDA:: [!] Decompilation interrupted.

![image](https://user-images.githubusercontent.com/21986859/77122285-27194580-6a35-11ea-9d69-dd6f248fd0c3.png)

I found some test samples from the "Practical Malware Analysis" book (specifically Lab13-01.exe), and observed something interesting. The Ghidra headless analysis will succeed, but only after the full 300 seconds times out. If the decompilation is interrupted by clicking "Cancel" after a few seconds, the decompilation will still succeed. However, the decompilation will finish successfully within seconds for some binaries.

I believe I'm experiencing something similar to https://github.com/Cisco-Talos/GhIDA/issues/3#issuecomment-599059181. However, fixes in this comment, as well as other fixes in #3 didn't fix my problem.

**Comment by BullyWiiPlaza** [comment]
Same here, I tried 2 different EXEs and same result, it doesn't work. My `IDA` is `v7.2.0`. I use `Python 2` and the respective release.

```
GhIDA Decompiler v0.1
Andrea Marcelli <anmarcel@cisco.com>
Cisco Talos, June 2019
GhIDA Decompiler shortcut key is Ctrl-Alt-D
============================================================
GhIDA:: [DEBUG] Reading GhIDA configuration
('GHIDA_CONF.load_save_cached_code', False)
('GHIDA_CONF.load_save_cached_comments', False)
GhIDA:: [DEBUG] code_cache_path: c:\users\superu~1\appdata\local\temp\decompiled_cache_2FEAD5D997CA8F76C3F6176D9D3190EA.json
GhIDA:: [DEBUG] comments_cache_path: c:\users\superu~1\appdata\local\temp\comments_cache_2FEAD5D997CA8F76C3F6176D9D3190EA.json
GhIDA:: [DEBUG] Registering handlers
GhIDA [DEBUG] ScreenEAHook initialized
---------------------------------------------------------------------------------------------
Python 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)] 
IDAPython 64-bit v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
---------------------------------------------------------------------------------------------
('GHIDA_CONF.global_settings', True)
('GHIDA_CONF.use_ghidra_server', False)
('GHIDA_CONF.ghidra_install_path', 'D:\\Programs\\Portable\\Reverse Engineering\\ghidra_9.1.2_PUBLIC')
('GHIDA_CONF.ghidra_server_url', 'http://localhost:8080/ghidra/api')
('GHIDA_CONF.show_settings', True)
('GHIDA_CONF.load_save_cached_code', False)
('GHIDA_CONF.load_save_cached_comments', False)
GhIDA:: [INFO] Configuration saved to c:\users\superu~1\appdata\local\temp\ghida_config.json
GhIDA:: [DEBUG] EXPORT_XML_FILE: True
GhIDA:: [DEBUG] Exporting IDA project into XML format

XML Exporter v5.0.1 : SDK 720
-----------------------------------------------------------
Exporting XML <PROGRAM> document ....
Processing PROGRAM                 GhIDA:: [DEBUG] compiler name: Visual C++
GhIDA:: [DEBUG] new_compiler_name: Visual C++
CPU time: 0.0097
Processing DATATYPES               CPU time: 0.0462
Processing MEMORY_MAP              CPU time: 150.4703
Processing REGISTER_VALUES         CPU time: 0.0015
Processing CODE                    CPU time: 26.5412
Processing DATA                    CPU time: 233.3852
Processing COMMENTS                CPU time: 70.1464
Processing PROGRAM_ENTRY_POINTS    CPU time: 0.0095
Processing SYMBOL_TABLE            CPU time: 23.6893
Processing FUNCTIONS               CPU time: 76.9884
Processing MARKUP                  CPU time: 303.6365
                             Total CPU time: 885.5619
--------------------------------------
PROGRAM                           1
INFO_SOURCE                       1
PROCESSOR                         1
COMPILER                          1
DATATYPES                         1
STRUCTURE                        38
MEMBER                          235
UNION                             4
ENUM                              2
ENUM_ENTRY                       10
MEMORY_MAP                        1
MEMORY_SECTION                    6
MEMORY_CONTENTS                  13
REGISTER_VALUES                   1
REGISTER_VALUE_RANGE             19
CODE                              1
CODE_BLOCK                   154120
DATA                              1
DEFINED_DATA                1002114
TYPEINFO_CMT                 320549
COMMENTS                          1
COMMENT                      226752
PROGRAM_ENTRY_POINTS              1
PROGRAM_ENTRY_POINT             211
SYMBOL_TABLE                      1
SYMBOL                        98276
FUNCTIONS                         1
FUNCTION                      73979
ADDRESS_RANGE                 83664
STACK_FRAME                   73028
STACK_VAR                    241139
REPEATABLE_CMT                   55
MARKUP                            1
MEMORY_REFERENCE             342017
--------------------------------------
Total XML Elements:         2616245
Database exported to: D:\Executables\2FEAD5D997CA8F76C3F6176D9D3190EA_lMRMs.xml
GhIDA:: [DEBUG] found 0 symbols
GhIDA:: [INFO] XML exporting completed
GhIDA:: [DEBUG] decompiled cache miss (180514340)
GhIDA:: [DEBUG] Decompiling 180514340
GhIDA:: [DEBUG] EXPORT_XML_FILE: False
GhIDA:: [INFO] Ghidra headless (timeout: 300s)
GhIDA:: [INFO] Waiting Ghidra headless analysis to finish...
GhIDA:: [INFO] Ghidra analysis completed!
GhIDA:: [!] No JSON object could be decoded
GhIDA:: [!] Ghidra headless analysis failed
GhIDA:: [!] Decompilation interrupted.
```

**Comment by jimmy-sonny** [comment]
I've checked the binaries that you reported in the issue:
- GreenBug Trojan: 5d204ca32a5ed72511decd3245b6cf4731378e5b5e0bf8eb5acb8069adf5136d
- GameAssembly.dll
416129f967752d22afcead9a771250810057eaaa8ae6f9f390596dd60824cae6

In both cases the Ghidra headless analysis is particularly long and it causes the failure in the GhIDA plugin.

Regarding the GreenBug Trojan, the CFG of `000000013F0CC130` is complex, and Ghidra requires slightly less than 5 mins on Linux to decompile it. On windows the time was higher, but it could be related to the JVM settings.

Regarding GameAssembly.dll, the binary is about 30MB and unfortunately the Ghidra analysis takes more than 5minute. Changing the timeout in GhIDA to a much higher value is required.

I could not find any bug in the plugin itself since I believe the root cause is the time required by Ghidra to decompile the function.

**Comment by k4yt3x** [comment]
I did change the timeout from 300 to 3000, but it didn't work out either.
I encountered this error with various other binaries, while hexrays decompiler finishes in near seconds.
I'm not sure whether this difference is expected, or I have misconfigured something.

**Comment by jimmy-sonny** [comment]
If they are not private, please give me the sha256 of the binaries and the addresses of the functions that are causing the issue. I'll further debug the problem. Thanks

**Comment by thewavelength** [comment]
`1a651ddcc2c9997524c4eee89e73b0f97b43478286cf2249926d728cce390eb2  OLLYDBG.EXE`

I used OLLYDBG 1.10 as a simple example. Doesn't matter which function I try, GhIDA immediately reports analysis failed. You can use the function `_Findsymbolicname` as a reference. Using the latest release of GhIDA and ghidra (0.9.12)

```GhIDA:: [DEBUG] EXPORT_XML_FILE: False
GhIDA:: [DEBUG] decompiled cache miss (40b0a8)
GhIDA:: [DEBUG] Decompiling 40b0a8
GhIDA:: [DEBUG] EXPORT_XML_FILE: False
GhIDA:: [INFO] Ghidra headless (timeout: 300s)
GhIDA:: [INFO] Waiting Ghidra headless analysis to finish...
GhIDA:: [INFO] Ghidra analysis completed!
GhIDA:: [!] No JSON object could be decoded
GhIDA:: [!] Ghidra headless analysis failed
GhIDA:: [!] Decompilation interrupted.```

**Comment by alt-fox** [comment]
I got same error. 
do: analyzeHeadless.bat 123 Temp -import "12345.xml"
result: problem this import xml: INFO  No load spec found for import file

but I do this: analyzeHeadless.bat 123 Temp -import "12345.xml" -processor "x86:LE:32:default"
result: all is ok

**Comment by Zorro9999** [comment]
Good day. There is a problem as described above. Here is the log from Ida Pro.
``
  bytes   pages size description
--------- ----- ---- --------------------------------------------
   262144    32 8192 allocating memory for b-tree...
    65536     8 8192 allocating memory for virtual array...
   262144    32 8192 allocating memory for name pointers...
-----------------------------------------------------------------
   589824            total memory allocated

Loading processor module C:\Program Files\IDA 7.2\procs\i5164.dll for 8051...OK
Loading type libraries...
Autoanalysis subsystem has been initialized.
Database for file '307.bin' has been loaded.
============================================================
GhIDA Decompiler v0.1
Andrea Marcelli <anmarcel@cisco.com>
Cisco Talos, June 2019
GhIDA Decompiler shortcut key is Ctrl-Alt-D
============================================================
GhIDA:: [DEBUG] Reading GhIDA configuration
('GHIDA_CONF.load_save_cached_code', False)
('GHIDA_CONF.load_save_cached_comments', False)
GhIDA:: [DEBUG] code_cache_path: c:\users\user\appdata\local\temp\decompiled_cache_FE46C519975BC6E312BB1719D93A0A64.json
GhIDA:: [DEBUG] comments_cache_path: c:\users\user\appdata\local\temp\comments_cache_FE46C519975BC6E312BB1719D93A0A64.json
GhIDA:: [DEBUG] Registering handlers
GhIDA [DEBUG] ScreenEAHook initialized
---------------------------------------------------------------------------------------------
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] 
IDAPython 64-bit v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
---------------------------------------------------------------------------------------------
GhIDA:: [DEBUG] DisasmsHandler HELLO
('GHIDA_CONF.global_settings', True)
('GHIDA_CONF.use_ghidra_server', False)
('GHIDA_CONF.ghidra_install_path', 'E:\\ghidra_9.1.2_PUBLIC_20200212\\ghidra_9.1.2_PUBLIC')
('GHIDA_CONF.ghidra_server_url', 'http://localhost:8080/ghidra/api')
('GHIDA_CONF.show_settings', True)
('GHIDA_CONF.load_save_cached_code', False)
('GHIDA_CONF.load_save_cached_comments', False)
GhIDA:: [INFO] Configuration saved to c:\users\user\appdata\local\temp\ghida_config.json
GhIDA:: [DEBUG] EXPORT_XML_FILE: True
GhIDA:: [DEBUG] Exporting IDA project into XML format

XML Exporter v5.0.1 : SDK 720
-----------------------------------------------------------
Exporting XML <PROGRAM> document ....
Processing PROGRAM                 GhIDA:: [DEBUG] compiler name: Unknown
GhIDA:: [DEBUG] new_compiler_name: default
CPU time: 0.0019
Processing MEMORY_MAP              CPU time: 0.0061
Processing CODE                    CPU time: 0.0013
Processing DATA                    CPU time: 0.0507
Processing COMMENTS                CPU time: 0.0032
Processing PROGRAM_ENTRY_POINTS    CPU time: 0.0005
Processing SYMBOL_TABLE            CPU time: 0.0023
Processing FUNCTIONS               CPU time: 0.0041
Processing MARKUP                  CPU time: 0.0275
                             Total CPU time: 0.4666
--------------------------------------
PROGRAM                           1
INFO_SOURCE                       1
PROCESSOR                         1
COMPILER                          1
MEMORY_MAP                        1
MEMORY_SECTION                    4
MEMORY_CONTENTS                   2
CODE                              1
CODE_BLOCK                        9
DATA                              1
DEFINED_DATA                     62
TYPEINFO_CMT                    109
COMMENTS                          1
COMMENT                          27
PROGRAM_ENTRY_POINTS              1
PROGRAM_ENTRY_POINT               8
SYMBOL_TABLE                      1
SYMBOL                           29
FUNCTIONS                         1
FUNCTION                         50
ADDRESS_RANGE                    60
REPEATABLE_CMT                    7
MARKUP                            1
--------------------------------------
Total XML Elements:             379
Database exported to: E:\RABOTA\FE46C519975BC6E312BB1719D93A0A64_vnzEm.xml
GhIDA:: [DEBUG] found 0 symbols
GhIDA:: [INFO] XML exporting completed
GhIDA:: [DEBUG] decompiled cache miss (432)
GhIDA:: [DEBUG] Decompiling 432
GhIDA:: [DEBUG] EXPORT_XML_FILE: False
GhIDA:: [INFO] Ghidra headless (timeout: 1000s)
GhIDA:: [INFO] Waiting Ghidra headless analysis to finish...
GhIDA:: [INFO] Ghidra analysis completed!
GhIDA:: [!] No JSON object could be decoded
GhIDA:: [!] Ghidra headless analysis failed
GhIDA:: [!] Decompilation interrupted.

``
