### ISSUE TITLE
Sync Onclick Error

### ISSUE THREAD

**Issue by nipunjaswal** [Cisco-Talos/GhIDA#2]
The Plugin is Amazing. However, i came across this issue on clicking one of the code lines in the decompiled function:
![2019-09-06 (1)](https://user-images.githubusercontent.com/5489140/64410777-625fb280-d0a9-11e9-8696-41cf2e0b8356.png)

```
IDAPython: Error while calling Python callback <OnClick>:
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins/ghida.py", line 495, in OnClick
    return gl.highlight_symbol_in_DISASM()
  File "C:/Program Files/IDA 7.0/plugins\ghida_plugin\ui.py", line 52, in highlight_symbol_in_DISASM
    symbol = idaapi.get_highlighted_identifier()
  File "C:\Program Files\IDA 7.0\python\ida_kernwin.py", line 190, in get_highlight
    return _ida_kernwin.get_highlight(*args)
TypeError: get_highlight expected 1 arguments, got 0
```

**Comment by jimmy-sonny** [comment]
I've addressed this issue in https://github.com/Cisco-Talos/GhIDA/commit/adb455215813acaf84cf369beb4baea9a30cb1f0:  I've changed the API call from `get_highlighted_identifier` to `get_highlight` as suggested in the IDA7 python [documentation](https://www.hex-rays.com/products/ida/support/ida74_idapython_no_bc695_porting_guide.shtml).

If possible, please test it.
