### ISSUE TITLE
About disassembly

### ISSUE THREAD

**Issue by E4ck** [Cisco-Talos/GhIDA#20]
Can the plugin support disassembly of arm architecture?

I use it to disassemble the arm program and an error occurs:

{"SHOW_SETTINGS": true, "USE_GHIDRA_SERVER": false, "load_save_cached_code": false, "GHIDRA_INSTALLATION_PATH": "D:\\Ghidra_9.1.2", "load_save_cached_comments": false}

**Comment by jimmy-sonny** [comment]
In the current version, the plugin handles only x86/64 PE and ELF files. Adding the support for other architectures requires to update the [idaxml](https://github.com/Cisco-Talos/GhIDA/blob/master/ghida_plugin/idaxml.py) file.
