### ISSUE TITLE
Bug in calling tag_remove

### ISSUE THREAD

**Issue by HongThatCong** [Cisco-Talos/GhIDA#22]
ida_lines.tag_remove(regcmt + " ", 0) => ida_lines.tag_remove(regcmt + " ")
ida_lines.tag_remove(rptcmt + " ", 0) => ida_lines.tag_remove(rptcmt + " ")

Thanks, best regards,

**Comment by jimmy-sonny** [comment]
Related to https://github.com/NationalSecurityAgency/ghidra/issues/748.
Thanks @HongThatCong
