### ISSUE TITLE
Decompilation interrupted

### ISSUE THREAD

**Issue by nextdimension** [Cisco-Talos/GhIDA#23]
WIndows 10 - 20H2
IDA 7.5_pack3
GHIDRA 9.2.1 and 9.3
PYTHON 3.9.1

Tried multiple small binaries.

The analysis completes very fast and I can see the XML is populated, however I get this in the IDA log:

GhIDA:: [INFO] XML exporting completed
GhIDA:: [INFO] Ghidra headless (timeout: 5000s)
GhIDA:: [INFO] Waiting Ghidra headless analysis to finish...
GhIDA:: [INFO] Ghidra analysis completed!
GhIDA:: [!] Expecting value: line 1 column 1 (char 0)
GhIDA:: [!] Ghidra headless analysis failed
GhIDA:: [!] Decompilation interrupted.

**Comment by jimmy-sonny** [comment]
Hi! Thanks for reporting this issue. Can you please try with Ghidra version 9.1.2? It may be related to [this](https://github.com/NationalSecurityAgency/ghidra/issues/2561) bug in Ghidra.

**Comment by nextdimension** [comment]
Confrimed working on Ghidra version 9.1.2.

**Comment by TheDuchy** [comment]
If anyone like me installed JRE instead of a JDK and got this error, here is your problem.
