### ISSUE TITLE
Doesn't work with master build of Ghidra

### ISSUE THREAD

**Issue by mendax47** [Cisco-Talos/GhIDA#5]
![image](https://user-images.githubusercontent.com/6140928/64487241-aabdd280-d259-11e9-9a3b-ad1ebf507ceb.png)

IDA Pro 7.2
Ghidra Master Build (Last Commit)

**Comment by jimmy-sonny** [comment]
Can you please give me more information? Does it work on other binaries?

**Comment by mendax47** [comment]
No, it doesn't work at all...

**Comment by jimmy-sonny** [comment]
@mendax47 Can you please share the mini dump file? Otherwise I don't have enough information to address this issue.
